esphome:
  name: aquarium
  platform: ESP8266
  board: huzzah

substitutions:
  otapassword: ThisIsABadIdea
  ssid: Foobar
  networkkey: ThisIsAlsoABadIdea

<<: !include common.yaml

debug:

logger:
  level: debug

dallas:
  - pin: 13

sensor:
  - platform: dallas
    address: 0x6400000b95eb6628
    name: "Aquarium Temperature"
  - platform: wifi_signal
    name: "Aquarium Sensors WiFi Signal Strength"
  - platform: uptime
    name: "Aquarium Sensors Uptime"

binary_sensor:
  - platform: status
    name: "Aquarium Sensors Status"