esphome:
  name: aquarium
  platform: ESP8266
  board: huzzah

substitutions:
  otapassword: ThisIsABadIdea
  ssid: Foobar
  networkkey: ThisIsAlsoABadIdea

<<: !include common.yaml

debug:

logger:
  level: debug

dallas:
  - pin: 13

sensor:
  - platform: dallas
    index: 0
    # address: 0x2866eb950b000064
    name: "Aquarium Temperature"
  - platform: wifi_signal
    name: "Aquarium Sensors WiFi Signal Strength"
  - platform: uptime
    name: "Aquarium Sensors Uptime"